# Generated by Django 5.2.10 on 2026-01-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_username_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Пользователь"
            ),
        ),
    ]
