# Generated by Django 5.2.10 on 2026-02-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
