# Generated by Django 5.2.10 on 2026-01-09 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habbit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Введите место для выполнения привычки",
                        max_length=150,
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="Введите время и дату выполнения привычки"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите действие, которое представляет собой привычка",
                        max_length=200,
                    ),
                ),
                (
                    "is_rewarding",
                    models.BooleanField(
                        default=False, help_text="Укажите, если это приятная привычка"
                    ),
                ),
                (
                    "periodicity_days",
                    models.IntegerField(
                        default=1,
                        help_text="Периодичность привычки в днях",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "reward_text",
                    models.CharField(
                        blank=True,
                        help_text="Укажите награду после выполнения привычки",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        help_text="Укажите продолжительность выполнения привычки (в секундах, максимум 120)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, если хотите сделать привычку общедоступной",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите привычку, связанную с новой привычкой",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habbits.habbit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["id"],
            },
        ),
    ]
